---
title: "Studiedesign"
bibliography: 
  referanser/04-ref.bib
editor_options: 
  chunk_output_type: console
---


## Introduksjon

Studiedesign er en viktig komponent i forskning da det vil være avgjørende for hvordan data samles inn, tolkes og analyseres. Ifølge Zabor et al. (2020) vil et godt studiedesign ofte resultere i mer pålitelige resultater og større grad av reproduserbarhet, samt minimere bias [@Zabor2020]. Bias innen statistikk refererer til enhver skjevhet eller feil i eksperimentdesignet eller datainnsamlingsprosessen, som gir resultater som ikke nøyaktig representerer populasjonen [@Gutbezahl2017].

Struktur er en viktig komponent når man planlegger en studie. QALMRI-metoden kan bidra til å sikre en ryddig og god struktur. QALMRI adresserer spørsmål som en ønsker svar på, for så å oppgi hvilke tilnærminger som skal benyttes for å besvare spørsmålet. Videre ser man på sammenhengen mellom metodene som benyttes i studien og koblingen til spørsmålet man har stilt i oppgaven. Til slutt presenteres resultatene og man drar konklusjoner til den aktuelle populasjonen. 

I denne oppgaven studeres fem originalartikler som tar for seg effekten av blokkperiodisering på $\dot{V}O_{2max}$ [@Ronnestad2019; @Breil2010; @Ronnestad2016; @Ronnestad2014; @Ronnestad2014_2]. I oppgaven blir det lagt mest vekt på studiedesignene og de statistiske analysemetodene fra de utvalgte studiene, samt en vurdering av styrker og svakheter knyttet til disse. 

## Metode

Alle studiene i oppgaven er randomiserte kontrollerte forsøk (RCT) der man var interessert i å undersøke effekten av periodisering av høyintensiv trening. Utvalget ble delt i to grupper, en  blokkperiodiseringsgruppe (BP) og en kontrollgruppe (CT). I studiene trente utvalget i BP og CT det samme volumet totalt over intervensjonsperioden. Forskjellen var at BP periodiserte sine høyintesive økter i bolker/mikrosykluser (periodiserignen varierte mellom studiene). Det ble gjennomført målinger både pre og post treningsintervensjonen og intervensjonene hadde varighet fra 4 til 12 uker.

I studiene lå utvalget et sted mellom 16 og 22 personer. I noen studier så en på både kvinner og menn, i andre studier kun menn. Gjengangeren var at utvalget ble definert som godt trente utøvere, eller at de hadde drevet kompetetivt i sin idrett de siste årene.

Det ble gjennomført ulike statistiske analyser i de ulike forsøkene. Noen benyttet ANOVA, mens andre benyttet *t*-tester, eller en kombinasjon av begge. Flere av studiene benyttet Cohen's d for å beregne effektstørrelse (ES) da dette er en gunstig å benytte når en vil vurdere effekten av en intervensjon og sammenlinkne to grupper. I oppgaven er tolkningen av effektstørrelse som følger: lav effekt = 0.2, moderat effekt = 0.5, stor effekt = 0.8 og veldig stor effekt > 1.0 [@Hopkins2009].

I studiene ble resultater presentert som gjennomsnittsøkning i % $\pm$ standardavvik. Resultater ble ansett som statistisk signifikante dersom *p*-verdier $\leq$ 0.05. 

## Resultater

Etter å ha sammenliknet kontrollgruppen med blokkperiodiseringsgruppen post intervensjon, kom samtlige studier frem til at blokkperiodisering gav signinfikant økning i prestasjonsparametere. Endringene kan ses i @tbl-endringvo2.  

*P*-verdier < 0.05 i samtlige studier. Den gjennomsnittlige effekten ble målt til å ligge en plass mellom 0.76 og 1.34 i 4/5 studier. En av studiene gjorde i tillegg beregninger på kun de mannlige utøverne i sin studie og fant mer signifikante resultater. Denne studien presenterte ingen effektstørrelser.  

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: tbl-endringvo2
#| tbl-cap: "Endringer i BP-gruppen"

library(tidyverse)
library(gt)

endring_bp <- data.frame(
  Studie = 1:5,
  Relativ_endring_i_VO2max = c("5.1 \u00b1 3.3%", "5.1 \u00b1 na", "2.0 \u00b1 2.5%", "4.6 \u00b1 3.7%", "8.8 \u00b1 5.9%"),
  p_verdi = c("=0.05", "<0.01", "<0.05", "<0.05", "<0.05"),
  Effektstorrelse = c(1.04, NA, 0.76, 1.34, 1.08))

endring_bp |> 
  gt() |> 
  cols_label(Relativ_endring_i_VO2max = md("Endring VO<sub>2max</sub>"),
             p_verdi = md("*P*-verdi"), 
             Effektstorrelse = md("Effektst&oslash;rrelse")) |> 
  tab_footnote(footnote = md("Resultat for statistiske tester")) |> 
  tab_style(cell_text(align = "center"), 
            locations = cells_body(everything()))

```




## Diskusjon


Ifølge Zabor et al. (2020) er en av styrkene ved å bruke RCT som studiedesign at det reduserer bias og gir et solid grunnlag for sammenligning av lignende intervensjoner. Dette designet bidrar til økt pålitelighet i resultatene. Videre gjør bruken av objektive data studiene mer anvendelige, ettersom det letter sammenligningen på tvers av ulike intervensjoner [@Zabor2020]. 

I lys av avsnittet over kan en diskutere begrepet konfunding, som refererer til en tredje variabel som påvirker både den avhengige og uavhengige variabelen i studien [@VanderWeele2019]. I dette tilfellet kan den avhengige variabel være prestasjonsparametere og den uavhengige variabelen være treningsintervensjonen. Den tredje variabelen (konfunderen) kan i dette tilfellet være søvnkvalitet. Dersom man ikke tar høyde for den tredje variabelen, kan man trekke feilaktige konklusjoner om effekten av treningsintervensjonen. 

En svakhet ved studiene er de små utvalgene. Dette øker sjansen for å gjøre type II-feil (godtakelse av nullhypotesen, tross at den er falsk). Gjennomsnitt i små utvalg påvirkes i relativt stor grad av verdier som ligger langt unna gjennomsnittet (outliers) [@Mishra2019]. For å objektivt fjerne outliers fra datasettet kan en bestemme seg for grenseverdier man ønsker at sine verdier skal ligge innenfor [@Hopkins2009]. Dette kan dog by på probelmer. Hva som betraktes som en outlier kan variere avhengig av konteksten, spørsmålet man ønsker svar på og datamengden. Å bestemme seg for en forhåndsbestemt grense fjerner dessuten ideen om objektivitet, noe som er en av hovedpoengene med å bruke et RCT-design. 

Tid og varighet av intervensjoner er ofte en svakhet i studier. Disse studiene varte i henholdvis 5, 4, 5, 6 og 12-uker, noe som gjør det vanskelig å si noe om de langsiktige effektene av blokkperiodisering vs tradisjonell trening. Funnene i studiene kan styrkes dersom man studiene repeteres og/eller følges opp over lengre perioder. 

Målet med studiene var å se hvorvidt mikrosykluser med høyintensiv trening øker prestasjonsparameteren $\dot{V}O_{2max}$ mer enn traidisjonell periodisering av trening. For å undersøke potensielle endringer mellom BP og CT i studiene ble det som nevnt benyttet ulike statistsike tester. Grunnet små utvalg og en forventet liten endring i prestasjonsmaraterne blant de godt trente utøverne, ble det benyttet *t*-tester, da det viser seg hensiksmessig ved små utvalg og benyttes for å sammenlikne gjennomsnittet mellom to grupper [@Mishra2019].  

ANOVA kan ha blitt brukt for å analysere endringer i prestasjonsparametere over tid ved å sammenligne flere grupper på forskjellige tidspunkter i intervensjonen. Denne tilnærmingen gjør det mulig å vurdere effekten av periodiseringen av trening og hvordan prestasjonen utviklet seg over tid. Ved å bruke gjentatte målinger ANOVA kan en vurdere om effekten av blokkperiodisering i forhold til tradisjonell trening er signifikant forskjellig på flere tidspunkter underveis i intervensjonen. Dette gir en bedre forståelse av hvordan de ulike treningsmetodene påvirker prestasjon på lang sikt.

Flere av studiene benyttet Cohen's d for å beregne effektstørrelse (ES) da dette er en gunstig å benytte når en vil vurdere effekten av en intervensjon og sammenlinkne to grupper [@Hopkins2009]. Med Cohen's d får en standardisert forskjellen mellom gruppene og en kan sammenlikne effekter på tvers av studier hvor det benyttes ulikt design eller ulike måleenheter. I tillegg til å vurdere statistisk signifikans (*p*-verdi), gir Cohen's d informasjon om praktisk betydning av resultatene. Selv om en effekt kan være statistisk signifikant, kan en liten effekt indikere at forskjellen mellom gruppene ikke er stor nok til å ha praktisk relevans. En annen viktig ting å påpeke når en benytter Cohen's d, er at utvalgene bør være representative for populasjonen en ønsker å si noe om, slik at resultatene kan generaliseres på en pålitelig måte. Hvis utvalget er skjevt eller lite representativt for målgruppen, kan en risikere å trekke feilaktige konklusjoner om intervensjonens effekt.

Fremtidige studier bør inkludere større mangfold, som menn og kvinner, ulike aldersgrupper og treningsbakgrunner, for å kunne generalisere funnene til en bredere populasjon. Samtidig må utvalget være representativt for den populasjonen man ønsker å trekke inferens fra. For eksempel, hvis målet er å utvikle treningsmetoder for toppidrettsutøvere i sykling, bør utvalget bestå av godt trente syklister. Ettersom de eksisterende studiene primært har brukt godt trente utøvere, antyder dette at blokkperiodisering kan være særlig gunstig for denne gruppen, men begrenser muligheten for å generalisere til en bredere populasjon.

## Konklusjon

Blokkperiodisering har vist seg å gi større økning i $\dot{V}O_{2max}$ sammenlignet med tradisjonell trening, særlig blant godt trente utøvere som kan ha stagnert med tradisjonell trening. Designet i studiene er randomiserte kontrollerte forsøk, som styrker validiteten og gir et solid grunnlag for å sammenligne treningsmetoder. Det parallelle gruppedesignet som ble benyttet i disse studiene, gjør det mulig å isolere effekten av blokkperiodisering.

Et viktig hensyn er at utvalget i studiene hovedsakelig består av godt trente utøvere, noe som kan begrense generaliserbarheten til bredere populasjoner. For å øke validiteten og relevansen av resultatene, vil det være nyttig å gjenta studiene med et mer variert utvalg, inkludert personer med ulik treningsbakgrunn, kjønn og alder.
